{% set component_name = "cmake" %}
{% set repo_name = "gz-" + component_name %}
{% set version = "3.0.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = repo_name + major_version %}
{% set component_version = component_name + major_version %}
{% set cxx_name = "lib" + name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gazebosim/{{ repo_name }}/archive/{{ repo_name }}{{ major_version }}_{{ version }}.tar.gz
    sha256: 01edf6b20c0f2f76dc48c3fa48bfeb4e82dd60186b82c0b34e38f7e1f53f21ac

build:
  number: 1

outputs:
  - name: {{ cxx_name }}
    script: build.sh  # [unix]
    script: bld.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - pkg-config
        - ninja
    test:
      commands:
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [not win]
        - if exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

  - name: {{ name }}
    build:
      run_exports:
        - {{ pin_subpackage(cxx_name, max_pin='x') }}
    requirements:
      run:
        - {{ pin_subpackage(cxx_name, exact=True) }}


about:
  home: https://github.com/gazebosim/gz-cmake
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A set of CMake modules that are used by the C++-based Gazebo projects.'

extra:
  recipe-maintainers:
    - wolfv
    - traversaro
    - j-rivero

